class Constants:
    RIGHT_PASSWORD = '098765'
    WRONG_PASSWORD = '123'
    RETRIEVE_PASSWORD = '09887665'
    ONE_TIME_PASSWORD = '111111'
    EMAIL = 'dugaeva_10@gmail.com'
    URL = 'https://stellarburgers.nomoreparties.site'
    URL_REG = 'https://stellarburgers.nomoreparties.site/register'
    URL_LOG = 'https://stellarburgers.nomoreparties.site/login'
    URL_PROFILE = 'https://stellarburgers.nomoreparties.site/account/profile'
    URL_RESET = 'https://stellarburgers.nomoreparties.site/reset-password'
    URL_LOGO = 'https://stellarburgers.nomoreparties.site/'
    FORGOT_PASSWORD = 'https://stellarburgers.nomoreparties.site/forgot-password'
